spring:
  application:
    name: chili-chat
  profiles:
    group:
      default: local
      local: local
      dev: dev
      prod: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher