name: SERVER distribute

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd chili-chat-server
            sudo git pull
            sudo rm -r build/
            sudo ./gradlew build
            sudo java -jar build/libs/chilichat-0.0.1-SNAPSHOT.jar
            
